#Chap.4 numpy套件(numeric python)
#為什麼需要numpy?

* numpy由c撰寫，速度快python 10~1000倍以上
* numpy儲存結果較正確，python數字儲存不正確
* numpy節省記憶體儲存空間
* numpy的向量(矩陣計算)速度快
* numpy的取值方便



In [ ]:
a_list=[1,2,3,4,5]
print(a_list*3)  #會印出a_list的資料,而且是3遍

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
#numpy套件的ndarray型態,提供element-wise的操作
import numpy as np
a=np.array([1,2,3,4,5]) #把python内建轉成numpy np.array
print(a*3) #會印出每個都乘3的資料

[ 3  6  9 12 15]


In [ ]:
a=np.array([1,2,3,4,5])
print(type(a))
print(a.shape) #ndaary的形狀 #一維5個
print(a.dtype) #資料的型態
print(a.ndim) #維度

In [2]:
import numpy as np
z=np.zeros(6)
print(z) #會印出6個0
print(np.empty((2,3,4))) #會印出2筆資料,裡面會有各3行,並且每一行都有個4個0
print(np.arange(10))   #會印出0~9的數字

[0. 0. 0. 0. 0. 0.]
[[[1.2083154e-316 0.0000000e+000 0.0000000e+000 0.0000000e+000]
  [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]
  [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]]

 [[0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]
  [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]
  [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]]]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np
a=np.array([0,1,2,3,4])
print(a)  #印出a的資料
print(np.arange(5))  #印出5個數字,就是0~4

[0 1 2 3 4]
[0 1 2 3 4]


#2維資料取值

In [ ]:
my_2d_array=np.array([np.arange(0,5),np.arange(5,10)])
print(my_2d_array)  #從0開始到4和5到9的數字
print(my_2d_array[1,:]) #取第"1"維的值
print(my_2d_array[:,1]) #取第"0","1"維中,第"1"的值
print(my_2d_array[1,2]) #取第"1"維中,第"2"的值

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
7


In [ ]:
#更改維度reshape
a=np.arange(10) #一維10個數字
print(a)
b=a.reshape(2,5) #更改成二維,每維5個數字
print(b)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
